### ISSUE TITLE
I have OpenSSL issue with all of my machines running rvm

### ISSUE THREAD

**Issue by soheilbm** [onesky/onesky-ruby#6]
This is the error I get when I try to connect to your server. 

``` 
/Users/myHome/.rvm/gems/ruby-2.2.1/gems/rest-client-1.8.0/lib/restclient/request.rb:445:in `rescue in transmit': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (RestClient::SSLCertificateNotVerified)
	from /Users/myHome/.rvm/gems/ruby-2.2.1/gems/rest-client-1.8.0/lib/restclient/request.rb:350:in `transmit'
	from /Users/myHome/.rvm/gems/ruby-2.2.1/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
	from /Users/myHome/.rvm/gems/ruby-2.2.1/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
	from /Users/myHome/.rvm/gems/ruby-2.2.1/gems/rest-client-1.8.0/lib/restclient.rb:65:in `get'
	from /Users/myHome/.rvm/gems/ruby-2.2.1/gems/onesky-ruby-1.0.1/lib/onesky/helpers/request.rb:18:in `get'
	from /Users/myHome/.rvm/gems/ruby-2.2.1/gems/onesky-ruby-1.0.1/lib/onesky/resources/project/base.rb:18:in `list_language'
	from downloadLocals.ruby:20:in `<main>'
```

Is there any way to ignore peer verification of openssl ?

**Comment by VLMH** [comment]
Yes, there's way to by pass SSL verification but keep in mind that there will be no protection anymore
FYI, https://github.com/rest-client/rest-client/issues/288

May I know if you encounter the error with local machine?

**Comment by RomainBoulay** [comment]
Hey guys,

I have the exact same issue (from my local machine), is that caused by OneSky SSL's certificate?

Cheers.

**Comment by faucct** [comment]
Doubling this.
